CREATE TABLE table_one (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version         BIGINT       NOT NULL,
  str_type        VARCHAR(2),
  str_two         VARCHAR(255),
  str_name        VARCHAR(255) NOT NULL,
  date_created    TIMESTAMP,
  str_working     VARCHAR(1)   NOT NULL,
  last_updated    TIMESTAMP,
  str_one         VARCHAR(255),
  intg_no         INTEGER      NOT NULL,
  str_description VARCHAR(4000),
  dt_last         TIMESTAMP,
  dt_first        TIMESTAMP    NOT NULL,
  PRIMARY KEY (id)
);
ALTER TABLE table_one
  ADD CONSTRAINT UK_73phbw0ycoy7kv1yey8vijlgq UNIQUE (str_name);
