CREATE TABLE table_child (
  id           BIGINT NOT NULL,
  date_created TIMESTAMP,
  child_text   VARCHAR(255),
  last_updated TIMESTAMP,
  no           INTEGER,
  PRIMARY KEY (id)
);
CREATE TABLE table_child_two (
  id             BIGINT       NOT NULL,
  date_created   TIMESTAMP,
  last_updated   TIMESTAMP,
  no             INTEGER,
  child_two_text VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE table_one (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version         BIGINT       NOT NULL,
  str_type        VARCHAR(2),
  str_two         VARCHAR(255),
  str_name        VARCHAR(255) NOT NULL,
  date_created    TIMESTAMP,
  str_working     VARCHAR(1)   NOT NULL,
  last_updated    TIMESTAMP,
  str_one         VARCHAR(255),
  intg_no         INTEGER      NOT NULL,
  str_description VARCHAR(4000),
  dt_last         TIMESTAMP,
  dt_first        TIMESTAMP    NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE table_parent (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version BIGINT       NOT NULL,
  name    VARCHAR(255) NOT NULL,
  one_id  BIGINT       NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE table_three (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version      BIGINT  NOT NULL,
  str_type     VARCHAR(1),
  str_name     VARCHAR(255),
  date_created TIMESTAMP,
  age          INTEGER NOT NULL,
  last_updated TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE TABLE table_two (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  version      BIGINT       NOT NULL,
  str_type     VARCHAR(1),
  str_name     VARCHAR(255) NOT NULL,
  date_created TIMESTAMP,
  last_updated TIMESTAMP,
  three_id     BIGINT,
  intg_no      INTEGER      NOT NULL,
  str_note     VARCHAR(4000),
  PRIMARY KEY (id)
);
ALTER TABLE table_one
  ADD CONSTRAINT UK_73phbw0ycoy7kv1yey8vijlgq UNIQUE (str_name);
ALTER TABLE table_three
  ADD CONSTRAINT UK_a6gssmo12na95p8gb8o75h9r1 UNIQUE (str_name);
ALTER TABLE table_two
  ADD CONSTRAINT UK_8ve2ycp8ybkg695iljpmv6yfd UNIQUE (str_name);
ALTER TABLE table_parent
  ADD CONSTRAINT FKpff9pg3dgfuug0tr7qq6uac5g FOREIGN KEY (one_id) REFERENCES table_one;
ALTER TABLE table_two
  ADD CONSTRAINT FKi457f2dsvtyhpef6ms5ujrk2t FOREIGN KEY (three_id) REFERENCES table_three;
